apiVersion: apps/v1
kind: Deployment
metadata:
    name: mssql-tools
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mssql-tools
    template:
        metadata:
            labels:
                app: mssql-tools
        spec:
            containers:
            - name: mssql-tools
              image: mcr.microsoft.com/mssql-tools
              args: ["sleep", "infinity"]